site_name: K32 Docs
site_url: https://k32.pythonanywhere.com/
site_description: Documentação do K32
site_author: Felipe Bastos
copyright: Copyright &copy 2020 - 2023 Felipe Bastos

repo_url: https://github.com/felipebastos/rise/
repo_name: Rise
theme:
  name: material
  language: pt-BR
  logo: assets/k32.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: black
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: blue
      accent:  deep orange
      toggle:
        icon: material/brightness-4
        name: Mudar para modo escuro
  features:
    - search.suggest
    - navigation.footer

extra:
  social:
    - type: github
      icon: fontawesome/brands/github
      link: https://github.com/felipebastos/
      name: Felipe Bastos

plugins:
  - mkdocstrings
  - search

nav:
  - Home: index.md
  - Referências:
    - Players: players.md
    - MGE: mge.md
  - Sobre: about.md
