[tool.poetry]
name = "rise"
version = "0.1.0"
description = "A project to manage a Rise of Kingdoms kingdom"
authors = ["Felipe Bastos <felipe.bstosn@gmail.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0.1"
django-simple-captcha = "^0.5.14"
python-dotenv = "^0.19.2"
djangorestframework = "^3.13.1"
djangorestframework-simplejwt = "^5.0.0"
django-filter = "^21.1"

[tool.poetry.dev-dependencies]
pylint = "^2.9.2"
pytest = "^6.2.4"
autopep8 = "^1.5.7"
black = "^21.12b0"
requests = "^2.27.1"

[tool.black]
line-length = 80
include = '\.pyi?$'


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
