# Generated by Django 4.2.10 on 2024-03-02 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0026_alter_player_game_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoGH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateField(auto_now_add=True, verbose_name="Criado em"),
                ),
                ("data_evento", models.DateField(verbose_name="Data do evento")),
            ],
        ),
        migrations.CreateModel(
            name="InscritoGH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.BigIntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                (
                    "inserido",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Inserido"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ghevent.eventogh",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
    ]
