# Generated by Django 4.2.10 on 2024-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ghevent", "0002_eventogh_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventogh",
            name="anotacao",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
