# Generated by Django 3.2.5 on 2021-07-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_auto_20210707_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="semana",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bank.semana",
            ),
        ),
    ]
