# Generated by Django 3.2.5 on 2021-07-07 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_alter_donation_semana"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="semana",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="bank.semana",
            ),
        ),
        migrations.AlterField(
            model_name="semana",
            name="encerrada",
            field=models.BooleanField(
                default=False, verbose_name="Trabalhos concluídos"
            ),
        ),
    ]
