# Generated by Django 4.1 on 2022-09-08 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0023_alter_player_status"),
        ("bank", "0005_semana_recurso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("quantidade", models.BigIntegerField()),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.alliance",
                    ),
                ),
            ],
        ),
    ]
