# Generated by Django 4.1 on 2022-09-08 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0023_alter_player_status"),
        ("bank", "0006_credito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credito",
            name="ally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="players.alliance",
                verbose_name="Aliança",
            ),
        ),
        migrations.AlterField(
            model_name="credito",
            name="quantidade",
            field=models.BigIntegerField(verbose_name="Quantidade em milhões"),
        ),
    ]
