# Generated by Django 4.1 on 2022-09-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0007_alter_credito_ally_alter_credito_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credito",
            name="quantidade",
            field=models.FloatField(verbose_name="Quantidade em milhões"),
        ),
    ]
