# Generated by Django 5.1.1 on 2024-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0008_alter_credito_quantidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="credito",
            name="diferenca",
            field=models.FloatField(blank=True, default=0, verbose_name="Diferença"),
        ),
    ]
