# Generated by Django 4.1 on 2022-08-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0022_alter_advertencia_inicio_alter_playerstatus_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lado",
                    models.CharField(
                        choices=[("a", "Time A"), ("b", "Time B")], max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marcha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("inf", "Infantaria"),
                            ("arq", "Arquearia"),
                            ("cav", "Cavalaria"),
                            ("mis", "Mista"),
                            ("mqt", "Melhor que tiver"),
                        ],
                        default="mqt",
                        max_length=4,
                    ),
                ),
                (
                    "tarefa",
                    models.CharField(
                        choices=[
                            ("open", "Open field"),
                            ("guar", "Guarnição"),
                            ("rall", "Rally"),
                            ("swad", "Swarm defensivo"),
                            ("swao", "Swarm ofensivo"),
                        ],
                        default="open",
                        max_length=4,
                    ),
                ),
                (
                    "estrutura",
                    models.CharField(
                        choices=[
                            ("obda", "Obelisco defensivo A"),
                            ("obdb", "Obelisco defensivo B"),
                            ("oboa", "Obelisco ofensivo A"),
                            ("obob", "Obelisco ofensivo B"),
                            ("sagd", "Santuário da Guerra defensivo"),
                            ("sago", "Santuário da Guerra ofensivo"),
                            ("alcd", "Altar do Céu defensivo"),
                            ("alco", "Altar do Céu ofensivo"),
                            ("aldd", "Altar do Deserto defensivo"),
                            ("aldo", "Altar do Deserto ofensivo"),
                            ("savd", "Santuário da Vida defensivo"),
                            ("savo", "Santuário da Vida ofensivo"),
                            ("poad", "Postos Avançados defensivos"),
                            ("poao", "Postos Avançados ofensivos"),
                            ("nenh", "Nenhuma estrutura"),
                        ],
                        default="nenh",
                        max_length=4,
                    ),
                ),
                (
                    "tarefa_especial",
                    models.CharField(
                        choices=[
                            ("rald", "Rally no obelisco defensivo"),
                            ("ralo", "Rally no obelisco ofensivo"),
                            ("arca", "Carregar arca"),
                            ("meio", "Ir para o meio"),
                            ("nenh", "Nenhuma"),
                        ],
                        default="nenh",
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ally",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.alliance",
                    ),
                ),
                ("funcoes", models.ManyToManyField(to="osiris.funcao")),
            ],
        ),
        migrations.AddField(
            model_name="funcao",
            name="marchas",
            field=models.ManyToManyField(to="osiris.marcha"),
        ),
        migrations.AddField(
            model_name="funcao",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.player"
            ),
        ),
    ]
