# Generated by Django 4.1 on 2022-08-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0022_alter_advertencia_inicio_alter_playerstatus_data"),
        ("osiris", "0002_alter_time_ally"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="ally",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="players.alliance",
            ),
        ),
    ]
