# Generated by Django 4.1 on 2022-08-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osiris", "0004_alter_time_ally"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marcha",
            name="tarefa",
            field=models.CharField(
                choices=[
                    ("open", "Open field"),
                    ("guar", "Guarnição"),
                    ("rall", "Líder de Rally"),
                    ("rall", "Encher Rally"),
                    ("swad", "Swarm defensivo"),
                    ("swao", "Swarm ofensivo"),
                ],
                default="open",
                max_length=4,
            ),
        ),
    ]
