# Generated by Django 4.1.2 on 2022-10-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prazo_inscricao_mge",
                    models.IntegerField(
                        choices=[
                            (5, "Terça-feira"),
                            (4, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (2, "Sexta-feira"),
                            (1, "Sábado"),
                            (0, "Domingo"),
                        ],
                        default=3,
                        verbose_name="Prazo para inscrição em MGE",
                    ),
                ),
                (
                    "encerra_ranking",
                    models.IntegerField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Segunda-feira"),
                            (2, "Terça-feira"),
                            (3, "Quarta-feira"),
                            (4, "Quinta-feira"),
                            (6, "Sexta-feira"),
                            (7, "Sábado"),
                        ],
                        default=4,
                        verbose_name="Prazo para inscrição em MGE",
                    ),
                ),
            ],
        ),
    ]
