# Generated by Django 4.1.2 on 2022-10-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="encerra_ranking",
            field=models.IntegerField(
                choices=[
                    (0, "Domingo"),
                    (1, "Segunda-feira"),
                    (2, "Terça-feira"),
                    (3, "Quarta-feira"),
                    (4, "Quinta-feira"),
                    (6, "Sexta-feira"),
                    (7, "Sábado"),
                ],
                default=4,
                verbose_name="Prazo para travar o ranking do MGE",
            ),
        ),
    ]
