# Generated by Django 4.1.2 on 2022-10-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_alter_siteconfig_encerra_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="banner",
            field=models.TextField(default=""),
        ),
    ]
