# Generated by Django 4.1.2 on 2022-10-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0003_siteconfig_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destaque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=144)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destaques",
                        to="config.siteconfig",
                    ),
                ),
            ],
        ),
    ]
