# Generated by Django 4.1.2 on 2022-10-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_destaque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destaque",
            name="texto",
            field=models.CharField(
                max_length=500, verbose_name="Texto do destaque"
            ),
        ),
    ]
