# Generated by Django 4.1.2 on 2022-10-25 22:38

from django.db import migrations, models

import equipments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30, unique=True)),
                (
                    "miniatura",
                    models.ImageField(
                        blank=True,
                        default="user_default/profile.jpg",
                        upload_to=equipments.models.picture_directory_path,
                    ),
                ),
            ],
        ),
    ]
