# Generated by Django 4.1.2 on 2022-10-25 23:09

from django.db import migrations, models
import equipments.models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spec",
                    models.CharField(
                        choices=[
                            ("arq", "Arquearia"),
                            ("cav", "Cavalaria"),
                            ("inf", "Infantaria"),
                            ("tod", "Geral"),
                        ],
                        default="tod",
                        max_length=3,
                        verbose_name="Especialidade",
                    ),
                ),
                ("valor", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="miniatura",
            field=models.ImageField(
                blank=True,
                default="defaults/equipment.jpg",
                upload_to=equipments.models.picture_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="buffs",
            field=models.ManyToManyField(to="equipments.buff"),
        ),
    ]
