# Generated by Django 4.1.2 on 2022-10-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "equipments",
            "0002_buff_alter_equipamento_miniatura_equipamento_buffs",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipamento",
            name="buffs",
        ),
        migrations.AddField(
            model_name="buff",
            name="equipamento",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buffs",
                to="equipments.equipamento",
            ),
            preserve_default=False,
        ),
    ]
