# Generated by Django 4.1.2 on 2022-10-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0003_remove_equipamento_buffs_buff_equipamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="buff",
            name="ativacao",
            field=models.FloatField(default=1, verbose_name="Ativação"),
            preserve_default=False,
        ),
    ]
