# Generated by Django 4.1.2 on 2022-10-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0004_buff_ativacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buff",
            name="ativacao",
            field=models.FloatField(default=1.0, verbose_name="Ativação"),
        ),
    ]
