# Generated by Django 4.1.2 on 2022-10-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0005_alter_buff_ativacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="slot",
            field=models.CharField(
                choices=[
                    ("cap", "Capacete"),
                    ("pei", "Peitoral"),
                    ("luv", "Luva"),
                    ("arm", "Armamento"),
                    ("cal", "Calça"),
                    ("bot", "Bota"),
                    ("ace", "Acessório esquerdo"),
                    ("acd", "Acessório direito"),
                ],
                default="cap",
                max_length=3,
            ),
        ),
    ]
