# Generated by Django 4.1.2 on 2022-10-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0007_alter_equipamento_miniatura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="slot",
            field=models.CharField(
                choices=[
                    ("cap", "Capacete"),
                    ("pei", "Peitoral"),
                    ("luv", "Luva"),
                    ("arm", "Armamento"),
                    ("cal", "Calça"),
                    ("bot", "Bota"),
                    ("ace", "Acessório esquerdo"),
                    ("acd", "Acessório direito"),
                ],
                default="",
                max_length=3,
            ),
        ),
    ]
