# Generated by Django 4.1.2 on 2022-10-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0008_alter_equipamento_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buff",
            name="spec",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("arq", "Arquearia"),
                    ("cav", "Cavalaria"),
                    ("inf", "Infantaria"),
                    ("tod", "Geral"),
                ],
                default="tod",
                max_length=3,
                verbose_name="Especialidade",
            ),
        ),
    ]
