# Generated by Django 4.1.2 on 2022-10-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0009_alter_buff_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="buff",
            name="status",
            field=models.CharField(
                choices=[
                    ("atq", "Ataque"),
                    ("def", "Defesa"),
                    ("sau", "Saúde"),
                    ("vel", "Velocidade"),
                ],
                default="atq",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="buff",
            name="spec",
            field=models.CharField(
                choices=[
                    ("arq", "Arquearia"),
                    ("cav", "Cavalaria"),
                    ("inf", "Infantaria"),
                    ("tod", "Geral"),
                ],
                default="tod",
                max_length=3,
                verbose_name="Especialidade",
            ),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="slot",
            field=models.CharField(
                choices=[
                    ("cap", "Capacete"),
                    ("pei", "Peitoral"),
                    ("luv", "Luva"),
                    ("arm", "Armamento"),
                    ("cal", "Calça"),
                    ("bot", "Bota"),
                    ("ace", "Acessório esquerdo"),
                    ("acd", "Acessório direito"),
                ],
                default="cap",
                max_length=3,
            ),
        ),
    ]
