# Generated by Django 4.1.2 on 2022-10-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipments",
            "0010_buff_status_alter_buff_spec_alter_equipamento_slot",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="ativacao",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="slot",
            field=models.CharField(
                choices=[
                    ("cap", "Capacete"),
                    ("pei", "Peitoral"),
                    ("luv", "Luva"),
                    ("arm", "Armamento"),
                    ("cal", "Calça"),
                    ("bot", "Bota"),
                    ("ace", "Acessório"),
                ],
                default="cap",
                max_length=3,
            ),
        ),
    ]
