# Generated by Django 4.1.2 on 2022-10-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0011_equipamento_ativacao_alter_equipamento_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipamento",
            name="ativacao",
        ),
    ]
