# Generated by Django 4.1.2 on 2022-10-31 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0012_remove_equipamento_ativacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="nome",
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.CreateModel(
            name="Conjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30, unique=True)),
                (
                    "buff_duo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conjunto_duo",
                        to="equipments.buff",
                    ),
                ),
                (
                    "buff_quadro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conjunto_quadro",
                        to="equipments.buff",
                    ),
                ),
                (
                    "buff_sexto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conjunto_sexto",
                        to="equipments.buff",
                    ),
                ),
                (
                    "conjunto",
                    models.ManyToManyField(to="equipments.equipamento"),
                ),
            ],
        ),
    ]
