# Generated by Django 4.1.2 on 2022-10-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0013_alter_equipamento_nome_conjunto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buff",
            name="status",
            field=models.CharField(
                choices=[
                    ("atq", "Ataque"),
                    ("def", "Defesa"),
                    ("sau", "Saúde"),
                    ("vel", "Velocidade"),
                    ("dbr", "Debuff de rage"),
                    ("car", "Dano de contra-ataque recebido"),
                    ("cac", "Dano de contra-ataque causado"),
                    ("dbr", "Debuff de rage"),
                    ("dbd", "Debuff de defesa"),
                    ("dbs", "Debuff de saúde"),
                    ("dvc", "Debuff de velocidade de cavalaria"),
                    ("esc", "Escudo"),
                    ("hab", "Dano de habilidade"),
                    ("ano", "Dano de ataque normal"),
                    ("bra", "Bônus de rage"),
                    ("bad", "Aumento de dano"),
                    ("baa", "Aumento de ataque em área"),
                    ("dbd", "Debuff de defesa"),
                ],
                default="atq",
                max_length=3,
            ),
        ),
    ]
