# Generated by Django 4.1.2 on 2022-10-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0014_alter_buff_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuffConjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spec",
                    models.CharField(
                        choices=[
                            ("arq", "Arquearia"),
                            ("cav", "Cavalaria"),
                            ("inf", "Infantaria"),
                            ("tod", "Geral"),
                        ],
                        default="tod",
                        max_length=3,
                        verbose_name="Especialidade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("atq", "Ataque"),
                            ("def", "Defesa"),
                            ("sau", "Saúde"),
                            ("vel", "Velocidade"),
                            ("dbr", "Debuff de rage"),
                            ("car", "Dano de contra-ataque recebido"),
                            ("cac", "Dano de contra-ataque causado"),
                            ("dbr", "Debuff de rage"),
                            ("dbd", "Debuff de defesa"),
                            ("dbs", "Debuff de saúde"),
                            ("dvc", "Debuff de velocidade de cavalaria"),
                            ("esc", "Escudo"),
                            ("hab", "Dano de habilidade"),
                            ("ano", "Dano de ataque normal"),
                            ("bra", "Bônus de rage"),
                            ("bad", "Aumento de dano"),
                            ("baa", "Aumento de ataque em área"),
                            ("dbd", "Debuff de defesa"),
                        ],
                        default="atq",
                        max_length=3,
                    ),
                ),
                ("valor", models.FloatField()),
                (
                    "ativacao",
                    models.FloatField(default=1.0, verbose_name="Ativação"),
                ),
                (
                    "conjunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buffs",
                        to="equipments.conjunto",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="conjunto",
            name="buff_duo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conjunto_duo",
                to="equipments.buffconjunto",
            ),
        ),
        migrations.AlterField(
            model_name="conjunto",
            name="buff_quadro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conjunto_quadro",
                to="equipments.buffconjunto",
            ),
        ),
        migrations.AlterField(
            model_name="conjunto",
            name="buff_sexto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conjunto_sexto",
                to="equipments.buffconjunto",
            ),
        ),
    ]
