# Generated by Django 4.1.2 on 2022-10-31 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipments", "0015_buffconjunto_alter_conjunto_buff_duo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conjunto",
            name="buff_duo",
        ),
        migrations.RemoveField(
            model_name="conjunto",
            name="buff_quadro",
        ),
        migrations.RemoveField(
            model_name="conjunto",
            name="buff_sexto",
        ),
        migrations.AddField(
            model_name="buffconjunto",
            name="pecas",
            field=models.IntegerField(
                choices=[("2", "2"), ("4", "4"), ("6", "6")], default="2"
            ),
        ),
        migrations.AlterField(
            model_name="buffconjunto",
            name="conjunto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buff_conjunto",
                to="equipments.conjunto",
            ),
        ),
    ]
