# Generated by Django 4.1.2 on 2022-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipments",
            "0016_remove_conjunto_buff_duo_remove_conjunto_buff_quadro_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="buffconjunto",
            name="pecas",
            field=models.IntegerField(
                choices=[("2", "2"), ("4", "4"), ("6", "6")],
                default="2",
                verbose_name="Peças",
            ),
        ),
    ]
