# Generated by Django 4.1.2 on 2022-10-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0017_alter_buffconjunto_pecas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buffconjunto",
            name="pecas",
            field=models.CharField(
                choices=[("2", "2"), ("4", "4"), ("6", "6")],
                default="2",
                max_length=1,
                verbose_name="Peças",
            ),
        ),
    ]
