# Generated by Django 4.1.2 on 2022-10-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_da_task",
                    models.CharField(
                        max_length=40, verbose_name="Nome da task"
                    ),
                ),
                (
                    "ultima_execucao",
                    models.DateTimeField(verbose_name="Última execução"),
                ),
            ],
        ),
    ]
