# Generated by Django 4.1.2 on 2022-10-19 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
