# Generated by Django 4.1.2 on 2022-10-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="descricao",
            field=models.CharField(
                default="Não fornecida",
                max_length=500,
                verbose_name="Descrição",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="script",
            field=models.CharField(default="", max_length=100, verbose_name="Script"),
        ),
        migrations.AlterField(
            model_name="task",
            name="nome_da_task",
            field=models.CharField(
                default="Não nomeada",
                max_length=40,
                verbose_name="Nome da task",
            ),
        ),
    ]
