# Generated by Django 4.1.2 on 2022-10-19 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_descricao_task_script_alter_task_nome_da_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="ID único"),
        ),
    ]
