# Generated by Django 4.1.2 on 2022-10-19 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="ID único"
            ),
        ),
    ]
