# Generated by Django 4.1.2 on 2022-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="ultima_execucao",
            field=models.DateTimeField(null=True, verbose_name="Última execução"),
        ),
    ]
