# Generated by Django 3.2.5 on 2021-07-23 20:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0016_auto_20210716_1614"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.IntegerField(unique=True)),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Mge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Criado em"
                    ),
                ),
                (
                    "inscritos",
                    models.ManyToManyField(
                        related_name="mge_inscritos",
                        through="mge.Inscrito",
                        to="players.Player",
                    ),
                ),
            ],
            options={
                "ordering": ["rank__id"],
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.IntegerField(unique=True)),
                (
                    "mge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mge.mge",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Punido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.IntegerField(unique=True)),
                (
                    "mge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mge.mge",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.AddField(
            model_name="mge",
            name="punidos",
            field=models.ManyToManyField(
                related_name="mge_punidos",
                through="mge.Punido",
                to="players.Player",
            ),
        ),
        migrations.AddField(
            model_name="mge",
            name="rank",
            field=models.ManyToManyField(
                related_name="mge_ranking",
                through="mge.Ranking",
                to="players.Player",
            ),
        ),
        migrations.AddField(
            model_name="inscrito",
            name="mge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mge.mge"
            ),
        ),
        migrations.AddField(
            model_name="inscrito",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.player"
            ),
        ),
    ]
