# Generated by Django 3.2.5 on 2021-07-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscrito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='punido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={},
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='punido',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='order_index',
        ),
    ]
