# Generated by Django 3.2.5 on 2021-07-23 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mge", "0002_auto_20210723_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscrito",
            name="inserido",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Inserido"
            ),
        ),
        migrations.AddField(
            model_name="punido",
            name="inserido",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Inserido"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="inserido",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Inserido"
            ),
        ),
    ]
