# Generated by Django 3.2.5 on 2021-07-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mge", "0003_auto_20210723_1722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscrito",
            name="inserido",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Inserido"
            ),
        ),
        migrations.AlterField(
            model_name="punido",
            name="inserido",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Inserido"
            ),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="inserido",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Inserido"
            ),
        ),
    ]
