# Generated by Django 3.2.5 on 2021-07-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mge", "0004_auto_20210723_1724"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mge",
            options={"ordering": ["criado_em"]},
        ),
        migrations.RemoveField(
            model_name="mge",
            name="inscritos",
        ),
        migrations.RemoveField(
            model_name="mge",
            name="punidos",
        ),
        migrations.RemoveField(
            model_name="mge",
            name="rank",
        ),
    ]
