# Generated by Django 4.0.1 on 2022-01-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mge', '0005_auto_20210723_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='kills',
            field=models.IntegerField(default=0),
        ),
    ]
