# Generated by Django 4.0.1 on 2022-02-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mge", "0006_inscrito_deaths_inscrito_kills"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscrito",
            name="general",
            field=models.TextField(default=""),
        ),
    ]
