# Generated by Django 4.0.2 on 2022-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mge", "0007_inscrito_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="mge",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("0", "Não definido"),
                    ("1", "Infantaria"),
                    ("2", "Cavalaria"),
                    ("3", "Arquearia"),
                    ("4", "Liderança"),
                    ("5", "Infantaria + Lançamento"),
                    ("6", "Cavalaria + Lançamento"),
                    ("7", "Arqueria + Lançamento"),
                    ("8", "Liderança + Lançamento"),
                ],
                default="0",
                max_length=2,
                verbose_name="Tipo",
            ),
        ),
    ]
