# Generated by Django 4.0.6 on 2022-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mge", "0010_eventodepoder"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscrito",
            name="intuito",
            field=models.BooleanField(default=False),
        ),
    ]
