# Generated by Django 4.0.6 on 2022-08-10 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mge", "0012_alter_inscrito_kills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventodepoder",
            name="inserido",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Inserido"
            ),
        ),
        migrations.AlterField(
            model_name="inscrito",
            name="inserido",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Inserido"
            ),
        ),
        migrations.AlterField(
            model_name="punido",
            name="inserido",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Inserido"
            ),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="inserido",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Inserido"
            ),
        ),
    ]
