# Generated by Django 4.1.7 on 2023-02-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mge", "0015_mge_inicio_das_inscricoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscrito",
            name="gh",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inscrito",
            name="prioridade",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inscrito",
            name="situacao",
            field=models.CharField(default="0000", max_length=5),
        ),
    ]
