# Generated by Django 3.2.5 on 2021-07-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(max_length=8)),
                ("nick", models.CharField(max_length=100)),
                ("power", models.IntegerField()),
                ("killpoints", models.IntegerField()),
                ("deaths", models.IntegerField()),
            ],
        ),
    ]
