# Generated by Django 3.2.5 on 2021-07-01 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tag", models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name="player",
            name="deaths",
        ),
        migrations.RemoveField(
            model_name="player",
            name="killpoints",
        ),
        migrations.RemoveField(
            model_name="player",
            name="power",
        ),
        migrations.AddField(
            model_name="player",
            name="rank",
            field=models.CharField(
                choices=[
                    ("R5", "R5"),
                    ("R4", "R4"),
                    ("R3", "R3"),
                    ("R2", "R2"),
                    ("R1", "R1"),
                ],
                default="R1",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("INATIVO", "Inativo"),
                    ("MIGROU", "Migrou"),
                    ("VIGIAR", "Vigiar"),
                    ("BANIDO", "BANIDO"),
                ],
                default="ATIVO",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="PlayerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=datetime.date.today)),
                ("power", models.IntegerField()),
                ("killpoints", models.IntegerField()),
                ("deaths", models.IntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="alliance",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.alliance",
            ),
        ),
    ]
