# Generated by Django 3.2.3 on 2021-07-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_auto_20210701_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="observacao",
            field=models.CharField(default="", max_length=500),
        ),
    ]
