# Generated by Django 3.2.3 on 2021-07-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_player_observacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="alliance",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.alliance",
            ),
        ),
    ]
