# Generated by Django 3.2.3 on 2021-07-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_alliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatus',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
