# Generated by Django 3.2.3 on 2021-07-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_alter_playerstatus_power"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="observacao",
            field=models.CharField(default="", max_length=500, null=True),
        ),
    ]
