# Generated by Django 3.2.5 on 2021-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_player_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
