# Generated by Django 3.2.5 on 2021-07-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0010_alter_player_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="observacao",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
