# Generated by Django 3.2.5 on 2021-07-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0011_alter_player_observacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("arq", "Arquearia"),
                    ("cav", "Cavalaria"),
                    ("lid", "Liderança"),
                    ("inf", "Infantaria"),
                    ("end", "Especialidade não definida"),
                ],
                default="end",
                max_length=30,
            ),
        ),
    ]
