# Generated by Django 3.2.5 on 2021-07-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_player_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='specialization',
            new_name='specialty',
        ),
    ]
