# Generated by Django 3.2.5 on 2021-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_rename_specialization_player_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('PLAYER', 'Player'), ('FARM', 'Farm'), ('INATIVO', 'Inativo'), ('MIGROU', 'Migrou'), ('VIGIAR', 'Vigiar'), ('BANIDO', 'BANIDO')], default='ATIVO', max_length=100),
        ),
    ]
