# Generated by Django 3.2.5 on 2021-07-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_alter_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='observacao',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
