# Generated by Django 3.2.8 on 2021-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20210716_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatus',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
