# Generated by Django 4.0.6 on 2022-08-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_alter_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatus',
            name='killpoints',
            field=models.BigIntegerField(),
        ),
    ]
