# Generated by Django 4.0.6 on 2022-08-10 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0021_alter_playerstatus_killpoints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertencia",
            name="inicio",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="playerstatus",
            name="data",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
