# Generated by Django 4.2 on 2023-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0023_alter_player_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="farms",
            field=models.ManyToManyField(related_name="principal", to="players.player"),
        ),
    ]
