# Generated by Django 4.2 on 2023-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0024_player_farms"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="func",
            field=models.CharField(
                choices=[
                    ("open", "Openfield"),
                    ("rali", "Rali"),
                    ("guar", "Guarnição"),
                ],
                default="open",
                max_length=4,
            ),
        ),
    ]
