# Generated by Django 4.2 on 2023-09-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0025_player_func"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="game_id",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
