# Generated by Django 4.2.10 on 2024-03-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0026_alter_player_game_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatus",
            name="killst4",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatus",
            name="killst5",
            field=models.BigIntegerField(default=0),
        ),
    ]
