# Generated by Django 3.2.5 on 2021-07-17 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kvk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inicio",
                    models.DateField(default=datetime.date.today, unique=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HA", "Hino Heróico"),
                            ("C8", "Conflito dos 8"),
                        ],
                        default="HA",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
