# Generated by Django 3.2.5 on 2021-07-24 18:53

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0016_auto_20210716_1614"),
        ("kvk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Levantado em",
                    ),
                ),
                (
                    "kvk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kvk.kvk",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.player",
                    ),
                ),
                (
                    "primeiro_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kvkprimeirostatus",
                        to="players.playerstatus",
                    ),
                ),
                (
                    "ultimo_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kvkultimostatus",
                        to="players.playerstatus",
                    ),
                ),
            ],
        ),
    ]
