# Generated by Django 3.2.5 on 2021-07-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0002_desempenho"),
    ]

    operations = [
        migrations.AddField(
            model_name="desempenho",
            name="honra",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="desempenho",
            name="zerado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kvk",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
