# Generated by Django 4.0.4 on 2022-06-25 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0018_alter_player_game_id"),
        ("kvk", "0004_zerado_kvk_final_delete_desempenho_zerado_kvk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdicionalDeFarms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t4_deaths", models.IntegerField(default=0)),
                ("t5_deaths", models.IntegerField(default=0)),
                (
                    "kvk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kvk.kvk",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.player",
                    ),
                ),
            ],
        ),
    ]
