# Generated by Django 4.0.6 on 2022-07-17 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvk', '0005_adicionaldefarms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('kvk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvk.kvk')),
            ],
        ),
    ]
