# Generated by Django 4.0.6 on 2022-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0006_etapas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapas",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
