# Generated by Django 4.0.6 on 2022-08-10 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0008_alter_zerado_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zerado",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
