# Generated by Django 4.1.2 on 2022-10-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0023_alter_player_status"),
        ("kvk", "0010_pontosdemge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[("ral", "Rali"), ("gua", "Guarnição")],
                        default="ral",
                        max_length=3,
                    ),
                ),
                (
                    "kvk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kvk.kvk",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.player",
                    ),
                ),
            ],
        ),
    ]
