# Generated by Django 4.1.7 on 2023-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0011_cargo"),
    ]

    operations = [
        migrations.AddField(
            model_name="kvk",
            name="primeira_luta",
            field=models.DateField(null=True),
        ),
    ]
