# Generated by Django 4.1.7 on 2023-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0012_kvk_primeira_luta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kvk",
            name="final",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kvk",
            name="primeira_luta",
            field=models.DateField(blank=True, null=True),
        ),
    ]
