# Generated by Django 4.2 on 2023-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0013_alter_kvk_final_alter_kvk_primeira_luta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kvk",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("HA", "Hino Heróico"),
                    ("C8", "Conflito dos 8"),
                    ("NI", "Nilo"),
                ],
                default="HA",
                max_length=2,
            ),
        ),
    ]
