# Generated by Django 4.2 on 2023-04-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvk", "0014_alter_kvk_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontosdemge",
            name="mortes",
            field=models.IntegerField(default=0),
        ),
    ]
