# Generated by Django 4.2 on 2023-05-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0023_alter_player_status"),
        ("kvk", "0015_pontosdemge_mortes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consolidado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posicao", models.IntegerField()),
                (
                    "cor",
                    models.CharField(
                        choices=[("GRE", "green"), ("YEL", "yellow"), ("RED", "red")],
                        default="GRE",
                        max_length=3,
                    ),
                ),
                ("kp", models.BigIntegerField()),
                ("dt", models.IntegerField()),
                ("zerado", models.BooleanField(default=False)),
                (
                    "kvk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kvk.kvk"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
    ]
