# Generated by Django 4.2 on 2023-05-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvk", "0016_consolidado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consolidado",
            name="cor",
            field=models.CharField(
                choices=[
                    ("GRA", "grey"),
                    ("GRE", "green"),
                    ("YEL", "yellow"),
                    ("RED", "red"),
                ],
                default="GRE",
                max_length=3,
            ),
        ),
    ]
