# Generated by Django 4.2 on 2023-07-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvk", "0017_alter_consolidado_cor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consolidado",
            old_name="cor",
            new_name="cor_dt",
        ),
        migrations.RenameField(
            model_name="consolidado",
            old_name="posicao",
            new_name="posicao_dt",
        ),
        migrations.AddField(
            model_name="consolidado",
            name="cor_kp",
            field=models.CharField(
                choices=[
                    ("GRA", "grey"),
                    ("GRE", "green"),
                    ("YEL", "yellow"),
                    ("RED", "red"),
                ],
                default="GRE",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="consolidado",
            name="posicao_kp",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
