# Generated by Django 4.2.10 on 2024-03-21 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0027_playerstatus_killst4_playerstatus_killst5"),
        ("kvk", "0019_alter_consolidado_posicao_kp"),
    ]

    operations = [
        migrations.CreateModel(
            name="KvKStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deatht4", models.IntegerField(default=0)),
                ("deatht5", models.IntegerField(default=0)),
                ("honra", models.IntegerField(default=0)),
                ("marauders", models.IntegerField(default=0)),
                (
                    "kvk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kvk.kvk"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
    ]
