# Generated by Django 5.1 on 2024-09-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kvk", "0020_kvkstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batalha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "descricao",
                    models.CharField(
                        choices=[
                            ("ND", "Não definido"),
                            ("Z5", "Zona 5"),
                            ("Z6", "Zona 6"),
                            ("KL", "Kingsland"),
                            ("DK", "Altar da Escuridão"),
                        ],
                        default="ND",
                        max_length=2,
                    ),
                ),
                (
                    "kvk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kvk.kvk"
                    ),
                ),
            ],
        ),
    ]
